### ISSUE TITLE
Jest throw error for the GoAModal with "open" property

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#1073]
**Version:**
UI component: @abgov/react-components@4.0.0-alpha.(from 114 to 129)
React: "18.2.0",

**Description:**
The GoAModel will throw an error in frontend unit test for a react application. The code used are listed, as follows:

```
import React from 'react';
import { GoAModal } from '@abgov/react-components-new';

export const TestComponent = (): JSX.Element => {
  return (
    <GoAModal heading="Do you agree?" open={true} onClose={() => {}}>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati id molestiae, natus dicta, eaque qui
        iusto similique, libero explicabo eligendi eius laboriosam! Repellendus ducimus officia asperiores. Eos, eius
        numquam.
      </p>
    </GoAModal>
  );
};
```

```
import { TestComponent } from './modalTest';
import React from 'react';
import { render  } from '@testing-library/react';
describe('Test Pdf list page', () => {
  it('Can create add edit pdf template', () => {
    render(<TestComponent></TestComponent>);
  });
});
```
The code will throw unexpected errors. Initial investigation indicates the error might be related to "open" property in the GoAModal.

**Comment by ArakTaiRoth** [comment]
@solittlework What's the error that's being thrown? Do you have a stack trace?

**Comment by solittlework** [comment]
Hi @ArakTaiRoth,

I've listed the stack trace as follows.  Do we have a unit test for the component in the ui-component?
```
    console.error
      Error: Uncaught [TypeError: Cannot read properties of null (reading 'insertRule')]
          at reportException (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeCEReactions (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:193:7)
          at ceReactionsPostSteps (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:54:3)
          at HTMLElement.setAttribute (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Element.js:215:9)
          at setValueForProperty (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:798:14)
          at setInitialDOMProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9720:7)
          at setInitialProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9921:3)
          at finalizeInitialChildren (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:10950:3)
          at completeWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:22193:17)
          at completeUnitOfWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26593:16) {
        detail: TypeError: Cannot read properties of null (reading 'insertRule')
            at create_rule (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:306:17)
            at go (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:565:32)
            at Object.start (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:602:10)
            at /Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:12780:21
            at flush (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:453:10)
            at HTMLElement.set open [as open] (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:13196:6)
            at HTMLElement.attributeChangedCallback (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:1032:19)
            at HTMLElement.invokeTheCallbackFunction (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)
            at invokeCEReactions (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:188:31)
            at ceReactionsPostSteps (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:54:3)
            at HTMLElement.setAttribute (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Element.js:215:9)
            at setValueForProperty (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:798:14)
            at setInitialDOMProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9720:7)
            at setInitialProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9921:3)
            at finalizeInitialChildren (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:10950:3)
            at completeWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:22193:17)
            at completeUnitOfWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26593:16)
            at performUnitOfWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26568:5)
            at workLoopSync (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
            at renderRootSync (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
            at performConcurrentWorkOnRoot (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:25738:74)
            at flushActQueue (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react/cjs/react.development.js:2667:24)
            at act (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react/cjs/react.development.js:2582:11)
            at /Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/act-compat.js:63:25
            at renderRoot (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/pure.js:159:26)
            at render (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/pure.js:246:10)
            at Object.<anonymous> (/Users/haipengli/workspace/projects/adsp-monorepo/apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/modalTest.spec.tsx:6:11)
            at Promise.then.completed (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/utils.js:333:28)
            at new Promise (<anonymous>)
            at callAsyncCircusFn (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/utils.js:259:10)
            at _callCircusTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:277:40)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at _runTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:209:3)
            at _runTestsForDescribeBlock (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:97:9)
            at _runTestsForDescribeBlock (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:91:9)
            at run (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:31:3)
            at runAndTransformResultsToJestFormat (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
            at jestAdapter (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
            at runTestInternal (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/runTest.js:411:16)
            at runTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/runTest.js:499:34)
            at Object.worker (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/testWorker.js:133:12),
        type: 'unhandled exception'
      }

      at VirtualConsole.<anonymous> (../../node_modules/jest-environment-jsdom/build/index.js:70:23)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at invokeCEReactions (../../node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:193:7)
      at ceReactionsPostSteps (../../node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:54:3)
      at HTMLElement.setAttribute (../../node_modules/jsdom/lib/jsdom/living/generated/Element.js:215:9)
      at setValueForProperty (../../node_modules/react-dom/cjs/react-dom.development.js:798:14)
      at setInitialDOMProperties (../../node_modules/react-dom/cjs/react-dom.development.js:9720:7)

    console.error
      Error: Uncaught [TypeError: Cannot read properties of null (reading 'insertRule')]
          at reportException (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:233:9)
          at DocumentImpl.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:715:12)
          at Document.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Document.js:278:60)
          at element (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:188:20)
          at Object.c (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:10116:19)
          at init (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:997:35)
          at new IconButton (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:10380:6)
          at Function.invokeTheCallbackFunction.construct (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/CustomElementConstructor.js:23:30)
          at createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:204:33) {
        detail: TypeError: Cannot read properties of null (reading 'insertRule')
            at create_rule (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:306:17)
            at go (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:565:32)
            at Object.start (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:602:10)
            at /Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:12789:21
            at flush (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:453:10)
            at init (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:1002:6)
            at new Icon (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:10817:6)
            at Function.invokeTheCallbackFunction.construct (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/CustomElementConstructor.js:23:30)
            at createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:204:33)
            at DocumentImpl.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:715:12)
            at Document.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Document.js:278:60)
            at element (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:188:20)
            at Object.c (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:10116:19)
            at init (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:997:35)
            at new IconButton (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:10380:6)
            at Function.invokeTheCallbackFunction.construct (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/CustomElementConstructor.js:23:30)
            at createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:204:33)
            at DocumentImpl.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:715:12)
            at Document.createElement (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Document.js:278:60)
            at element (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:188:20)
            at Object.c (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:12934:26)
            at Object.p (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:12735:22)
            at Object.p (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:13010:21)
            at update (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:475:33)
            at flush (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:435:8)
            at HTMLElement.set closable [as closable] (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:13185:6)
            at HTMLElement.attributeChangedCallback (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@abgov/react-components-new/react-components.umd.js:1032:19)
            at HTMLElement.invokeTheCallbackFunction (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)
            at invokeCEReactions (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:188:31)
            at ceReactionsPostSteps (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:54:3)
            at HTMLElement.setAttribute (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jsdom/lib/jsdom/living/generated/Element.js:215:9)
            at setValueForProperty (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:798:14)
            at setInitialDOMProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9720:7)
            at setInitialProperties (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:9921:3)
            at finalizeInitialChildren (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:10950:3)
            at completeWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:22193:17)
            at completeUnitOfWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26593:16)
            at performUnitOfWork (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26568:5)
            at workLoopSync (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
            at renderRootSync (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
            at performConcurrentWorkOnRoot (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react-dom/cjs/react-dom.development.js:25738:74)
            at flushActQueue (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react/cjs/react.development.js:2667:24)
            at act (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/react/cjs/react.development.js:2582:11)
            at /Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/act-compat.js:63:25
            at renderRoot (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/pure.js:159:26)
            at render (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/@testing-library/react/dist/pure.js:246:10)
            at Object.<anonymous> (/Users/haipengli/workspace/projects/adsp-monorepo/apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/modalTest.spec.tsx:6:11)
            at Promise.then.completed (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/utils.js:333:28)
            at new Promise (<anonymous>)
            at callAsyncCircusFn (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/utils.js:259:10)
            at _callCircusTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:277:40)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at _runTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:209:3)
            at _runTestsForDescribeBlock (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:97:9)
            at _runTestsForDescribeBlock (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:91:9)
            at run (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/run.js:31:3)
            at runAndTransformResultsToJestFormat (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
            at jestAdapter (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
            at runTestInternal (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/runTest.js:411:16)
            at runTest (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/runTest.js:499:34)
            at Object.worker (/Users/haipengli/workspace/projects/adsp-monorepo/node_modules/jest-runner/build/testWorker.js:133:12),
        type: 'unhandled exception'
      }

      at VirtualConsole.<anonymous> (../../node_modules/jest-environment-jsdom/build/index.js:70:23)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at createElement (../../node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:233:9)
      at DocumentImpl.createElement (../../node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:715:12)
      at Document.createElement (../../node_modules/jsdom/lib/jsdom/living/generated/Document.js:278:60)
      at element (../../node_modules/@abgov/react-components-new/react-components.umd.js:188:20)
      at Object.c (../../node_modules/@abgov/react-components-new/react-components.umd.js:10116:19)
```

**Comment by ArakTaiRoth** [comment]
@solittlework I've investigated this issue. We do have tests for this very thing, you can find them at https://github.com/GovAlta/ui-components/blob/590a530419b5112461439a03d87a6444f119a3f7/libs/web-components/src/components/modal/Modal.spec.ts#L10 for the web-component unit tests, or here https://github.com/GovAlta/ui-components/blob/590a530419b5112461439a03d87a6444f119a3f7/libs/react-components/src/lib/modal/modal.spec.tsx#L8 for the react-component unit tests.

Our unit tests do all pass, and as you can see in our react test, we are also passing just a default "true" value for open. That all being said, I manually tested your code on a site, not in a test, and I can quickly replicate the error. This same error using the same method cannot be seen using just the standard web-components, so this issue is exclusive to React.

I've made a story here which you can follow if you're interested, https://goa-dio.atlassian.net/browse/DDIDS-1288

**Comment by solittlework** [comment]
@ArakTaiRoth, thank you so much for your investigation!

**Comment by vanessatran-ddi** [comment]
@solittlework Hello, 
I just want to let you know that the new release @abgov/react-components@4.10.0 should address your issue above.
