### ISSUE TITLE
[Bug]: Error of adding onclick event in the form stepper when the number of pages enlarged dynamically.

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#1695]
### Describe the bug

Ideally, the state and onclick event binding in the GoAFormStepper and related components will be refreshed if the number of pages or original data is changed. However, adding extra entry in GoAFormStepper dynamically will lead to an error. The details can be seen from the code provided. 

### Provide Code
```javascript
import React, { useState } from 'react';
import { GoAFormStepper, GoAFormStep, GoAPages, GoAButton } from '@abgov/react-components-new';

const TestPage = (): JSX.Element => {
  const [step, setStep] = useState(-1);

  const pagesInit = [
    {
      text: 'Personal details',
    },
    {
      text: 'Employment history',
    },
    {
      text: 'References',
    }
  ];

  const [pages, setPages] = useState(pagesInit);
  return (
    <>
      <GoAButton
        onClick={() => {
          setPages([
            {
              text: 'Personal details',
            },
            {
              text: 'Employment history',
            },
          ]);
        }}
      >
        Less
      </GoAButton>
      <GoAButton
        onClick={() => {
          setPages([
            {
              text: 'Personal details',
            },
            {
              text: 'Employment history',
            },
            {
              text: 'References',
            },
            {
              text: 'References 2',
            },
          ]);
        }}
      >
        More
      </GoAButton>
      <GoAFormStepper
        testId="foo"
        onChange={(step) => {
          setStep(step);
        }}
      >
        {pages.map((page, index) => {
          return <GoAFormStep key={index} text={page.text}></GoAFormStep>;
        })}
      </GoAFormStepper>
      <GoAPages current={step} mb="3xl">
        {pages.map((page, index) => {
          return <div key={index}>{page.text}</div>;
        })}
      </GoAPages>
    </>
  );
};

export default TestPage;
```

### To Reproduce

* The bug will be shown by clicking the "More" button.

### Relevant console log output

```shell
console.js:213 [undefined] is an invalid form step status 
    at GoAFormStep (http://localhost:4200/vendor.js:4589:17)
    at goa-form-stepper
    at GoAFormStepper (http://localhost:4200/vendor.js:4595:3)
    at LandingPage (http://localhost:4200/main.js:32:45)
    at RenderedRoute (http://localhost:4200/vendor.js:250947:5)
    at Routes (http://localhost:4200/vendor.js:251394:5)
    at div
    at O (http://localhost:4200/vendor.js:277442:22877)
    at AppRouters
    at AppWithAuthContext (http://localhost:4200/main.js:58995:44)
    at Provider (http://localhost:4200/vendor.js:245723:3)
    at Fe (http://localhost:4200/vendor.js:277442:20652)
    at div
    at app_App
    at Router (http://localhost:4200/vendor.js:251326:15)
    at BrowserRouter (http://localhost:4200/vendor.js:246173:5)
```

**Comment by ArakTaiRoth** [comment]
@solittlework After investigation with our current alpha build, the console error is at least no longer present or an issue. There are various visual issues, and a newly created form step element isn't clickable (though you can still get there via a Next button).

However we aren't going to look into these issues, as a dynamic Form Stepper is not something we want to support at this time. We have documentation [here (Figma)](https://www.figma.com/file/aIRjvBzpIUH0GbkffjbL04/%E2%9D%96-Patterns-library-%7C-DDD?type=design&node-id=101-4102&mode=design) that outlines what we recommend you do if you have input elements that direct the flow of the form. Specifically we recommend building the form in a one question per page style, and direct the usage of the form that way, rather than use a Form Stepper, in that particular use case.
