### ISSUE TITLE
Text Area: component issues with reset()

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1704]
# Info

When you have a TextArea component on a page with a FormBuilder (it doesn't need to be tied to the FormBuilder), and you reset that form, the TextArea component either doesn't appear or stops working as intended. This is tied to `goaValue` and reactive forms. If you remove the reactive form control from the TextArea component, it all works fine as intended.

## Code

The code that can replicate the issue can be done in multiple ways:

```javascript
<div *ngIf="displaytestForm">
  <form [formGroup]="testForm">
    <goa-form-item label="Court date"  [error]="errors['courtdate']">
      <goa-input goaValue formControlName="courtdate"  width="243px" type="date"></goa-input>
    </goa-form-item>
    <goa-form-item label="Charge(s)" [error]="errors['charges']" helpText="From the Traffic Safety Act or Criminal Code of Canada">
      <goa-textarea goaValue [formControl]="testText" width="944px" countby="character" maxcount="500" />
    </goa-form-item>
  </form>
  <br />
  {{ testForm.controls["charges"].value }}
</div>
<br />
<hr />
<br />
<goa-button (_click)="onClick()">
  Reset
</goa-button>

import { Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'abgov-textarea',
  templateUrl: './textarea.component.html',
  styleUrls: ['./textarea.component.css']
})

export class TextAreaComponent {
  errors: { [key: string]: string } = {};
  displaytestForm = true;
  testText = new FormControl();

  testForm = this.fb.group({
    courtdate: ['',Validators.required],
    charges: ['',Validators.required],
  });

  constructor(private fb: FormBuilder,){}

  ngOnInit(): void {
    this.testForm.reset();
  }

  onClick() {
    console.log("reset");
    this.testForm.reset();
  }
}
```
The above code resets the form on `ngOnInit`, this means the TextArea component doesn't even appear. If you remove the `ngOnInit` and instead reset the form via the button. The TextArea component remains, and still records a value, but the character counter stops working.

## Console Logs

The following are the logs shown when you reset a form that has a TextArea component on the same page:
```javascript
main.ts:5 TypeError: Cannot read properties of null (reading 'length')
    at Mf.t.$$.update (TextArea.svelte:35:15)
    at re (Component.js:144:5)
    at new Lf (TextArea.svelte:36:67)
    at r.<anonymous> (Component.js:280:16)
    at Generator.next (<anonymous>)
    at fulfilled (main.js:24:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at _Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
```

## Acceptance Criteria:

1. You can safely `reset()` a form with a TextArea component on the same page

**Comment by ArakTaiRoth** [comment]
@Spark450 Reach out to JP regarding the use case behind resetting the form

**Comment by Spark450** [comment]
Spoke to Gesu (FSD), they have a workaround in place where they are writing code to clear each text area `SetValue ("")`

Being able to use `reset()` is still desirable, normal behaviour for Angular forms and the design system team will work on this at some point in the future. Given there is a satisfactory work around, the priority of this issue will be kept at medium.

**Comment by syedszeeshan** [comment]
PR #1959 should also fix this issue.

Sample playground test code below

html
```
<div *ngIf="displaytestForm" style="background-color: lightcyan;">
  <form [formGroup]="testForm">
    <goa-form-item label="Court date"  [error]="errors['courtdate']">
      <goa-input goaValue formControlName="courtdate"  width="243px" type="date"></goa-input>
    </goa-form-item>
    <goa-form-item label="Charge(s)" [error]="errors['charges']" helpText="From the Traffic Safety Act or Criminal Code of Canada">
      <goa-textarea goaValue formControlName="charges" width="944px" countby="character" maxcount="500" countby="character" />
    </goa-form-item>
  </form>
  <br />
  Live Value: {{ testForm.controls["charges"].value }}
</div>
<br />
<hr />
<br />
<goa-button (_click)="onClick()">
  Reset
</goa-button>
```

ts
```
import { Component } from "@angular/core";
import {FormBuilder, FormControl, FormGroup, Validators} from "@angular/forms";

@Component({
  selector: "abgov-text-area",
  templateUrl: "./text-area.component.html",
})
export class TextAreaComponent {
  errors: { [key: string]: string } = {};
  displaytestForm = true;
  testForm: FormGroup;


  constructor(private fb: FormBuilder){
    this.testForm = this.fb.group({
      courtdate: ['',Validators.required],
      charges: ['',Validators.required],
    });
  }

  ngOnInit(): void {
    this.testForm.reset();
  }

  onClick() {
    console.log("reset");
    this.testForm.reset();
  }
}

```
